name: post_list_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.0
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  flex_color_scheme: ^8.1.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  formz: ^0.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
